version: '3.8'
services:
  frontend:
    image: bouchja1/kdetosakra.cz:latest
    environment:
      NODE_ENV: production # this is basically only for /app/server.js, React has its own 'production' value
      APP_NAME: kdetosakracz_web
      PORT: 3000
      DOCKER: 1
    networks:
      - traefik
      - kdetosakra
    deploy:
      replicas: 1
      labels:
        traefik.enable: 'true'
        traefik.http.routers.kdetosakra-frontend.rule: Host('kdetosakra.cz')
        traefik.http.routers.kdetosakra-frontend.entrypoints: 'websecure'
        traefik.http.routers.kdetosakra-frontend.middlewares: "redirect-www-to-non-www@file"
        traefik.http.services.kdetosakra-frontend-svc.loadbalancer.server.port: 3000
        swarmpit.service.deployment.autoredeploy: "true"
      update_config:
        order: start-first
      resources:
        reservations:
          cpus: "0.1"
          memory: "50M"
        limits:
          cpus: "0.5"
          memory: "300M"

networks:
  traefik:
    external: true
  kdetosakra:
    external: true
