export const MIN_DISTANCE_FOR_POINTS_RANDOM = 250;
export const MAX_SCORE_PERCENT = 100;
export const MAX_PANORAMA_TRIES = 5;
export const DEFAULT_PANORAMA_TOLERANCE = 50;
export const TOTAL_ROUNDS_MAX = 5;
