const nicknames = [
    'mikuláš',
    'Lucifer',
    'bezhlavý rytíř',
    'bílá paní',
    'vodník',
    'obr',
    'čaroděj',
    'Paleček',
    'Sněhurka',
    'hloupý Honza',
    'chytrá horákyně',
    'jeskyňka',
    'Azrael',
    'Vochomůrka',
    'Mrazík',
    'Gargamel',
    'Motýl Emanuel',
    'Fantomas',
    'Strýček Skrblík',
    'Šupina',
    'Šebestová',
    'ježibaba',
    'Karkulka',
    'Myšpulín',
    'Homer Simpson',
    'Ijáček',
    'silák',
    'Drak Mrak',
    'Asterix',
    'Obelix',
    'Medvídek Pú',
    'Malenka',
    'Popelka',
    'šípková Růženka',
    'skřítek',
    'děda Mráz',
    'loupežník',
    'D.J. Šídlo',
    'DJ Loutna',
    'Lara Croft',
    'Dvanácterák',
    'Křídlošíp',
    'Pérák',
    'Náměsíčník',
    'Panoramix',
    'Papušík',
    'Raťafák',
    'Šedá dáma',
    'Tesák',
    'Bílý Tesák',
    'Pocahontas',
    'Tichošlápek',
    'Tlustý mnich',
    'Han Solo',
    'Hujer',
    'Terminátor',
    'Randle McMurphy',
    'Rocky Balboa',
    'Predátor',
    'HAL 9000',
    'Sarah Connor',
    'Kapitán Nemo',
    'Kapitán Demo',
    'Petr Pan',
    'Pan Tau',
    'Jack Sparrow',
    'Tarzan',
    'John Hammond',
    'Aquaman',
    'Jára Cimrman',
    'Hulk',
    'Vinnetou',
    'Old Shatterhand',
    'Sam Hawkens',
    'Nscho-tschi',
    'Frederic Santer',
    'Intschu-tschuna',
    'Klekih-petra',
    'Sherlock Holmes',
    'Mauglí',
    'Don Juan',
    'Hawkeye Pierce',
    'Radar',
    "Radar O'Reilly",
    'Maxwell Klinger',
    'Trapper John',
    'Frank Burns',
    'Margaret Houlihan',
    'Sherman T. Potter',
    'B. J. Hunnicutt',
    'Shrek',
    'Princezna Fiona',
    'Perníček',
    'Pinocchio',
    'Agent Smith',
    'Charles Winchester III ',
    'Otec Mulcahy',
    'Arnold Rimmer',
    'Kocour',
    'Kryton',
    'Dave Lister',
    'Holly',
    'Kristina Kochanská',
    'Bernard Black',
    'Manny Bianco',
    'Darth Vader',
    'Obi-Wan Kenobi',
    'Luke Skywalker',
    'Chewbacca',
    'R2-D2',
    'C-3PO',
    'Greedo',
    'Ufňukaná Uršula',
    'Vendelína Výstřednice',
    'Vrba mlátička',
    'Héfaistos',
    'Leia Organa',
    'Michael Corleone',
    'Pallas Athéna',
    'Penelopa',
    'Odysseus',
    'Batman',
    'Iron Man',
    'Indiana Jones',
    'Hannibal Lecter',
    'Superman',
    'James Bond',
    'Freddy Krueger',
    'Glum',
    'Aragorn',
    'Gandalf',
    'Legolas',
    'Bilbo Pytlík',
    'Sauron',
    'Frodo Pytlík',
    'Galadriel',
    'Gimli',
    'Samvěd Křepelka',
    'Saruman',
    'Elrond',
    'Boromir',
    'Smělír Brandorád',
    'Alois Nebel',
    'Stewie Griffin',
    'Peter Griffin',
    'Meg Griffin',
    'Lois Griffin',
    'Glenn Quagmire',
    'Brian griffin',
    'Joe Swanson',
    'Chris Griffin',
    'Otec Brown',
    'Umpa-lumpa',
    'Willy Wonka',
    'Jan Tleskač',
    'Stromovous',
    'Dědek Vrbák',
    'děd Vševěd',
    'ohnivý mužík',
    'Bender',
    'Philip J. Fry',
    'Ferda Mravenec',
    'Kapitán',
    'Mooncake',
    'Avocato',
    'Little Cato',
    'Gary Goodspeed',
    'Ash Graven',
    'Lord Commander',
    'KVN',
    'HUE',
    'Thor',
    'Star-Lord',
    'Clarence',
    'Sheryl Goodspeed',
    'Quinn Airgon',
    'Tribore Menendez',
    'Gaia',
    'Uranos',
    'Scooby-Doo',
    'Kronos',
    'Rheia',
    'Okeanos',
    'Téthys',
    'Sindibád',
    'Hyperion',
    'Hádés',
    'Poseidón',
    'Kraken',
    'Zeus',
    'Afrodita',
    'Athéna',
    'Arés',
    'Héraklés',
    'Kirké',
    'Kapitán Haddock',
    'Tintin',
    'Cipísek',
    'Turanga Leela',
    'Dr. John Zoidberg',
    'John Rambo',
    'Amy Wong',
    'profesor Hluchavka',
    'Michelangelo',
    'drak',
    'Otesánek',
    'Rumcajs',
    'hejkal',
    'kocour v botách',
    'černý pes',
    'žabí princ',
    'pták Ohnivák',
    'Mr. Bean',
    'Kojot Vilda',
    'Dean Moriarty',
    'Starouš Bull Lee',
    'Šmudla',
    'Gríma Červivec',
    'Sal Paradise',
    'Jack Kerouac',
    'Allen Ginsberg',
    'Ken Kesey',
    'Neal Cassady',
    'Davy Jones',
    'King Kong',
    'Detektiv Klubíčko',
    'Barnabáš Blouznivý',
    'Sirius Black',
    'Albus Brumbál',
    'Rumburak',
    'Spejbl',
    'Lábus',
    'Žeryk',
    'Rufus Brousek',
    'Vilemína Červotočková',
    'Dudley Dursley',
    'Hrdonožka',
    'Janus Paklíč',
    'Kapitán Hook',
    'bílá velryba',
    'Humphrey Říhal',
    'Bond girl',
    'Peregrin Bral',
    'Smělmír Brandorád',
    'Hrabě Drákula',
    'Eric Cartman',
    'Kenny McCormic',
    'Kyle Broflovski',
    'Leopold Stotch',
    'Randy Marsh',
    'Stan Marsh',
    'Ike Broflovski',
    'Jimbo',
    'Mr. Hankey',
    'Pan Mackey',
    'pan Klobouk',
    'Santa Claus',
    'Šéf',
    'Craig Tucker',
    'Docent Chocholoušek',
    'Joker',
    'Barbar Conan',
    'Brouk Pytlík',
    'Bugs Bunny',
    'Nestor Burma',
    'Grinch',
    "D'Artagnan",
    'Daredevil',
    'Deadpool',
    'Dj Arnoštek',
    'Doctor Strange',
    'Antoine Doinel',
    'Soudce Dredd',
    'Inspektor Dreyfus',
];

export default nicknames;
